services:
  routinator:
    image: nlnetlabs/routinator:0.15.1
    container_name: bgp_harvest_routinator
    ports:
      - "127.0.0.1:3323:3323"
      - "127.0.0.1:8323:8323"
    command:
      - server
      - --http
      - 0.0.0.0:8323
      - --rtr
      - 0.0.0.0:3323
    volumes:
      - rpki-cache:/home/routinator/.rpki-cache
    restart: unless-stopped

volumes:
  rpki-cache:
    driver: local
