services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: bgp_harvest_clickhouse
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:8123:8123"
    environment:
      CLICKHOUSE_DB: bgp
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
      - ../../src/bgp_harvest/clients/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
